### ISSUE TITLE
Database association

### ISSUE THREAD

**Issue by ton00987** [ton00987/Get-A-js#1]
I found a problem on link 2 models with many-to-many relationship.
I read this doc [http://docs.sequelizejs.com/manual/tutorial/associations.html](http://docs.sequelizejs.com/manual/tutorial/associations.html).
but I can't understand it.

**Comment by jirawatsaesu** [comment]
I follow the link but website show page not found

**Comment by ton00987** [comment]
I have already edited link. Can you access it?

**Comment by jirawatsaesu** [comment]
Try this:
https://stackoverflow.com/questions/22958683/how-to-implement-many-to-many-association-in-sequelize

**Comment by ton00987** [comment]
That was very helpful. I can associate models because of it.
